/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.MainFrame;

import GUI.Models.RoundedPasswordField;
import Models.MySQL;
import Models.UserBean;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.CardLayout;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.logging.FileHandler;
import java.util.logging.Logger;

/**
 *
 * @author hasun
 */
public final class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        setRoundedJFrame();
        initComponents();
        openPanel();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Resources/camIcon.jpg")));

    }

    public static Logger log1;
    public static FileHandler handler1;

    static {
        try {
            log1 = Logger.getLogger("log1");
            handler1 = new FileHandler("log.txt", true);
            log1.addHandler(handler1);
        } catch (Exception e) {

        }

    }

    private JPanel signInPanel;
    private JPanel errorMessagePanel;
    private CardLayout cardLayout;

    //signPanel
    private components.ButtonGradient buttonGradient1;
    private components.FTextField fTextField1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel10;
    private RoundedPasswordField roundedPasswordField1;

    //errorPanel
    private main.JImagePanel jImagePanel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;

    private void setRoundedJFrame() {
        setUndecorated(true);
        setSize(600, 450);
        setBackground(java.awt.Color.white);
        setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 50, 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jImagePanel1 = new main.JImagePanel();
        jLabel1 = new javax.swing.JLabel();
        jImagePanel3 = new main.JImagePanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 450));
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(276, 450));

        jImagePanel1.setImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/welcomeImage.jpeg"))); // NOI18N
        jImagePanel1.setSmoothRendering(true);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Designed & Developed By Helixaa Inc.  ");

        jImagePanel3.setCenterImage(true);
        jImagePanel3.setFitToPanel(true);
        jImagePanel3.setImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/logoB&D1.png"))); // NOI18N
        jImagePanel3.setOpaque(false);

        javax.swing.GroupLayout jImagePanel3Layout = new javax.swing.GroupLayout(jImagePanel3);
        jImagePanel3.setLayout(jImagePanel3Layout);
        jImagePanel3Layout.setHorizontalGroup(
            jImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        jImagePanel3Layout.setVerticalGroup(
            jImagePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 68, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jImagePanel1Layout = new javax.swing.GroupLayout(jImagePanel1);
        jImagePanel1.setLayout(jImagePanel1Layout);
        jImagePanel1Layout.setHorizontalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
            .addGroup(jImagePanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jImagePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jImagePanel1Layout.setVerticalGroup(
            jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jImagePanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jImagePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 278, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImagePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(324, 450));
        jPanel2.setPreferredSize(new java.awt.Dimension(324, 450));
        jPanel2.setLayout(new java.awt.CardLayout());
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void openPanel() {

        cardLayout = new CardLayout();
        jPanel2.setLayout(cardLayout);

        // Initialize the panels
        signInPanel = createSignInPanel();
        errorMessagePanel = createErrorMessagePanel();

        //adding panel to the jpanel2
        jPanel2.add(signInPanel, "SignIn");
        jPanel2.add(errorMessagePanel, "ErrorPanel");

        //show default layout
        cardLayout.show(jPanel2, "SignIn");
    }

    private JPanel createSignInPanel() {
        JPanel signinPanel = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(signinPanel);
        signinPanel.setLayout(layout);

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fTextField1 = new components.FTextField();
        jLabel9 = new javax.swing.JLabel();
        roundedPasswordField1 = new RoundedPasswordField();
        buttonGradient1 = new components.ButtonGradient();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(324, 450));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome Back !");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Enter Your Login Details");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Username");

        fTextField1.setCaretColor(new java.awt.Color(0, 0, 0));
        fTextField1.setLineColor(new java.awt.Color(7,45,132));
        fTextField1.setPreferredSize(new java.awt.Dimension(266, 39));
        fTextField1.setSelectedTextColor(new java.awt.Color(0, 0, 0));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Password");

        
        //5, 51, 47
        roundedPasswordField1.setLineColor(new java.awt.Color(7,45,132));
        roundedPasswordField1.setPreferredSize(new java.awt.Dimension(266, 39));

        buttonGradient1.setText("Login");
        buttonGradient1.setColor1(new java.awt.Color(7,45,132));
        buttonGradient1.setColor2(new java.awt.Color(7,45,132));
        buttonGradient1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonGradient1.setPreferredSize(new java.awt.Dimension(206, 39));
        buttonGradient1.setSizeSpeed(0.0F);
        buttonGradient1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1ActionPerformed(evt);

            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Exit");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                System.exit(0);
            }
        });

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)
                                                        .addComponent(fTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(roundedPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(61, 61, 61)
                                                .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(146, 146, 146)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(roundedPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(buttonGradient1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addContainerGap(62, Short.MAX_VALUE))
        );

        return signinPanel;

    }

    private JPanel createErrorMessagePanel() {

        JPanel errorPanel = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(errorPanel);
        errorPanel.setLayout(layout);

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jImagePanel2 = new main.JImagePanel();
        jLabel5 = new javax.swing.JLabel();

        errorPanel.setBackground(new java.awt.Color(255, 255, 255));
        errorPanel.setForeground(new java.awt.Color(255, 255, 255));
        errorPanel.setPreferredSize(new java.awt.Dimension(324, 450));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Something Wrong !");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Your Password Doesn’t Match. Please");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jImagePanel2.setFitToPanel(false);
        jImagePanel2.setImageHeight(130);
        jImagePanel2.setImageIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Error.png"))); // NOI18N
        jImagePanel2.setImageWidth(130);
        jImagePanel2.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout jImagePanel1Layout = new javax.swing.GroupLayout(jImagePanel2);
        jImagePanel2.setLayout(jImagePanel1Layout);
        jImagePanel1Layout.setHorizontalGroup(
                jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 130, Short.MAX_VALUE)
        );
        jImagePanel1Layout.setVerticalGroup(
                jImagePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 130, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cancel");
        jLabel5.setMinimumSize(new java.awt.Dimension(34, 16));
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR) {
        });
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cardLayout.show(jPanel2, "SignIn");
            }
        });

        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jImagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43)
                                .addComponent(jImagePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80))
        );

        return errorPanel;
    }

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {
        String username = fTextField1.getText();
        String password = String.valueOf(roundedPasswordField1.getPassword());

        try {

            if (username.isEmpty()) {
                showError("Please enter username");
            } else if (password.isEmpty()) {
                showError("Please enter password");
            } else if (password.length() > 16) {
                showError("Password too long");
            } else if (password.length() < 8) {
                showError("Password too short");
            } else {

                ResultSet resultSet = MySQL.execute("SELECT * FROM `user` INNER JOIN `user_type` ON `user`.`user_type_id` = `user_type`.`id` INNER JOIN `user_status` ON  `user_status`.`id`=`user`.`user_status_id` WHERE `username`='" + username + "' AND `password`='" + password + "'");
                if (resultSet.next()) {

                    int userStatus = resultSet.getInt("user_status_id");

                    if (userStatus == 1) {

                        UserBean userbean = new UserBean();
                        userbean.setNic(resultSet.getString("nic"));
                        userbean.setFirstName(resultSet.getString("fname"));
                        userbean.setLastName(resultSet.getString("lname"));
                        userbean.setUsername(resultSet.getString("username"));
                        userbean.setMobile(resultSet.getString("mobile_no"));
                        userbean.setStatus(resultSet.getString("user_status.status"));
                        userbean.setUserType(resultSet.getString("type"));

                        LocalDate loginDate = LocalDate.now();
                        LocalTime loginTime = LocalTime.now();

                        MySQL.execute("INSERT INTO `user_activity` (`user_nic`,`date`,`login_time`,`logout_time`) VALUE ('" + resultSet.getString("nic") + "','" + loginDate + "','" + loginTime + "','00:00:00')");

                        userbean.setLogInDate(String.valueOf(loginDate));
                        userbean.setLoginTime(String.valueOf(loginTime));

                        MainFrame mainFrame = new MainFrame(userbean);
//                        mainFrame.setUserBean(userbean);
                        mainFrame.setVisible(true);

                        this.dispose();
                    } else {
                        showError("Inactive User");
                    }
                } else {
                    showError("invalid User");
                }
            }
        } catch (Exception e) {
                       Login.log1.warning(e.getMessage());

        }
    }

    private void showError(String message) {
        JLabel errorLabel = (JLabel) ((JPanel) errorMessagePanel).getComponent(0);
        errorLabel.setText(message);
        cardLayout.show(jPanel2, "ErrorPanel");
        System.out.println(message);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private main.JImagePanel jImagePanel1;
    private main.JImagePanel jImagePanel3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
